### ISSUE TITLE
Problema al ejecutar el ejemplo cliente.

### ISSUE THREAD

**Issue by judlup** [ikeralbeniz/cellophane.io#2]
Buen dia, quisiera saber que puedo hacer en este caso:
http://www.subirimagenes.net/i/140401011748889786.png

ya que he intentado de muchas formas solucionarlo para poder ejecutarlo y no me ha salido nada, tambien quisiera saber si existe un ejemplo de servidor en cpp.

Gracias por su atencion prestada.
![problema](https://cloud.githubusercontent.com/assets/3951903/2574111/dbb488a0-b92a-11e3-8b87-b6f336cb7867.png)

**Comment by ikeralbeniz** [comment]
Please write in English in this board so everybody should have the posibility to understand this issue.

the problems you have is related to building usage basics, please learn a bit about building on linux:

http://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html

In case of cellophane io, before building examples be sure that the library is builded and installed:

$> make & sudo make install

this will build library and install header files and library on /usr/lib/libcellophane.so

do to build example client you should run

$> ggc example_client -o client -lcellophane
